project:
  type: website

execute:
  freeze: auto

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    toc: true

website:
  title: "Rodrygo Santos"
  navbar:
    background: light
    foreground: secondary
    left:
      - index.qmd
      - research.qmd
      - students.qmd
      - service.qmd
      - teaching.qmd
      - publications.qmd
      - contact.qmd
  sidebar:
    title: "Rodrygo Santos"
    logo: "rodrygo.png"
    pinned: true
    search: true
    footer: "[{{< iconify fa6-brands x-twitter size=1.2em >}}](https://twitter.com/rodrygo_santos) 
             [{{< iconify fa6-brands linkedin size=1.2em >}}](https://www.linkedin.com/in/rodrygo) 
             [{{< iconify fa6-brands github size=1.2em >}}](https://github.com/rodrygosantos) 
             [{{< iconify academicons lattes size=1.2em >}}](http://lattes.cnpq.br/1162362624079364) 
             [{{< iconify simple-icons dblp size=1.2em >}}](http://www.informatik.uni-trier.de/~ley/pers/hd/s/Santos:Rodrygo_L=_T=) 
             [{{< iconify fa6-brands google-scholar size=1.2em >}}](https://scholar.google.com/citations?user=NAyozE0AAAAJ)"



