---
title: "Research"
---

My research interests encompass large-scale [search](http://en.wikipedia.org/wiki/Search_engine_technology) and [recommendation](http://en.wikipedia.org/wiki/Recommender_system) in various domains, including the Web, social media, and enterprises. As a result of my work, I have contributed to the open-source [Terrier Information Retrieval platform](http://terrier.org/), and [published](/publications.html) research papers in several major academic venues. In particular, I am a regular speaker and program commitee member of several premiere conferences in IR, including [SIGIR](http://sigir.org/), [CIKM](http://www.cikmconference.org/), [WWW](http://www.wwwconference.org/), [WSDM](http://www.wsdm-conference.org/), [RecSys](http://recsys.acm.org/), [ECIR](http://irsg.bcs.org/ecir.php), [ICTIR](http://sigir.org/conferences/sponsored-conferences/), [AIRS](http://airs-conference.org/), and [SPIRE](https://link.springer.com/conference/spire). I received the [best paper award at RecSys 2015](http://recsys.acm.org/best-papers/) and [best paper runner-up award at RecSys 2020](http://recsys.acm.org/best-papers/). In addition, I have [served](/service.html) in the organization committee of [WSDM 2016](http://www.wsdm-conference.org/2016/), [RecSys 2020](https://recsys.acm.org/recsys20/), [SIGIR 2021](https://sigir.org/sigir2021/), [CIKM 2023](https://www.cikm2023.org/), and [UMAP 2024](https://www.um.org/umap2024/), and currently serve as steering committee member for [RecSys](https://recsys.acm.org/steering-committee/), and as a member of the editorial board of [ACM Transactions on Social Computing](https://dl.acm.org/journal/tsc/editorial-board) and [Foundations and Trends in Information Retrieval](https://www.nowpublishers.com/Journal/EditorialBoard/INR).

- [My Lattes CV](http://lattes.cnpq.br/1162362624079364)
- [My DBLP page](http://www.informatik.uni-trier.de/~ley/pers/hd/s/Santos:Rodrygo_L=_T=)
- [My Scholar profile](http://scholar.google.com/citations?user=NAyozE0AAAAJ)
