---
title: "Service"
---

## 2025

- Editorial Board member of ACM Transactions on Social Computing
- Editorial Board member of Found. and Trends in Information Retrieval
- Senior Program Committee member of ECIR 2025
- Senior Program Committee member of SIGIR 2025
- Steering Committee member of RecSys
- Tutorial co-chair of SIGIR 2025

## 2024

- Doctoral Consortium co-chair of UMAP 2024
- Editorial Board member of ACM Transactions on Social Computing
- Editorial Board member of Found. and Trends in Information Retrieval
- Senior Program Committee member of RecSys 2024
- Senior Program Committee member of SIGIR 2024
- Steering Committee member of RecSys

## 2023

- Editorial Board member of ACM Transactions on Social Computing
- Editorial Board member of Found. and Trends in Information Retrieval
- Program Committee co-chair of CIKM 2023
- Senior Program Committee member of RecSys 2023
- Senior Program Committee member of SIGIR 2023
- Steering Committee member of RecSys

## 2022

- Doctoral Consortium mentor of SIGIR 2022
- Editorial Board member of ACM Transactions on Social Computing
- Editorial Board member of Found. and Trends in Information Retrieval
- Program Committee member of SIGIR 2022
- Program Committee member of WWW 2022
- Senior Program Committee member of CIKM 2022
- Senior Program Committee member of RecSys 2022
- Steering Committee member of RecSys

## 2021

- Doctoral Consortium mentor of RecSys 2021
- Editorial Board member of ACM Transactions on Social Computing
- Editorial Board member of Found. and Trends in Information Retrieval
- Program Committee member of RecSys 2021
- Program Committee member of SIGIR 2021
- Program Committee member of WWW 2021
- Senior Program Committee member of CIKM 2021
- Steering Committee member of RecSys
- Tutorial co-chair of SIGIR 2021

## 2020

- Affiliate member of the Brazilian Academy of Sciences
- Editorial Board member of ACM Transactions on Social Computing
- Editorial Board member of Found. and Trends in Information Retrieval
- General co-chair of RecSys 2020
- Program Committee member of SIGIR 2020
- Program Committee member of WSDM 2020
- Program Committee member of WWW 2020
- Senior Program Committee member of CIKM 2020
- Steering Committee member of RecSys

## 2019

- Affiliate member of the Brazilian Academy of Sciences
- Editorial Board member of ACM Transactions on Social Computing
- Editorial Board member of Found. and Trends in Information Retrieval
- General co-chair of LARS 2019
- Program Committee member of ECIR 2019
- Program Committee member of RecSys 2019
- Program Committee member of SIGIR 2019
- Program Committee member of WSDM 2019
- Program Committee member of WWW 2019
- Senior Program Committee member of CIKM 2019
- Steering Committee member of RecSys

## 2018

- Affiliate member of the Brazilian Academy of Sciences
- Editorial Board member of ACM Transactions on Social Computing
- Editorial Board member of Found. and Trends in Information Retrieval
- Program Committee member of ECIR 2018
- Program Committee member of ICTIR 2018
- Program Committee member of RecSys 2018
- Program Committee member of SIGIR 2018
- Program Committee member of WSDM 2018
- Program Committee member of WWW 2018
- Senior Program Committee member of CIKM 2018

## 2017

- Affiliate member of the Brazilian Academy of Sciences
- Co-organizer of the MediaEval 2017 Retrieving Diverse Social Images task
- Editorial Board member of Found. and Trends in Information Retrieval
- Program Committee member of ECIR 2017
- Program Committee member of ICTIR 2017
- Program Committee member of LSRS at RecSys 2017
- Program Committee member of RecSys 2017
- Program Committee member of SIGIR 2017
- Program Committee member of WSDM 2017
- Program Committee member of WWW 2017
- Senior Program Committee member of CIKM 2017

## 2016

- Affiliate member of the Brazilian Academy of Sciences
- Editorial Board member of Found. and Trends in Information Retrieval
- Program Committee member of AIRS 2016
- Program Committee member of CIKM 2016
- Program Committee member of ECIR 2016
- Program Committee member of ICTIR 2016
- Program Committee member of QRUMS at WSDM 2016
- Program Committee member of SIGIR 2016
- Program Committee member of WSDM 2016
- Program Committee member of WWW 2016
- Senior Program Committee member of RecSys 2016
- Sponsorship co-chair of WSDM 2016

## 2015

- Editorial Board member of Found. and Trends in Information Retrieval
- Program Committee member of AIRS 2015
- Program Committee member of CIKM 2015
- Program Committee member of ECIR 2015
- Program Committee member of ICTIR 2015
- Program Committee member of RecSys 2015
- Program Committee member of SIGIR 2015
- Program Committee member of TWAW 2015

## 2014

- Editorial Board member of Found. and Trends in Information Retrieval
- Program Committee member of ECIR 2014
- Program Committee member of SIGIR 2014
- Program Committee member of SPIRE 2014

## 2013

- Program Committee member of CIKM 2013
- Program Committee member of ECIR 2013
- Program Committee member of ICTIR 2013
- Program Committee member of SIGIR 2013
- Program Committee member of SPIRE 2013
- Program Committee member of TWAW 2013

## 2012

- Program Committee member of CIKM 2012
- Program Committee member of DDR at WSDM 2012
- Program Committee member of ECIR 2012

## 2011

- Program Committee member of CIKM 2011
- Program Committee member of DDR at ECIR 2011
- Program Committee member of ECIR 2011
- Program Committee member of QRU at SIGIR 2011
